### ISSUE TITLE
Old importlib_metadata pin

### ISSUE THREAD

**Issue by maresb** [conda-forge/poetry-core-feedstock#13]
The current importlib-metadata version is 4.10.0, so the current pin of `<2.0.0` to maintain noarch is quite harsh. In order to alleviate extraneous conflicts for `py>=38`, I wonder if we should do an arch build, perhaps on another branch?

The same consideration applies to https://github.com/conda-forge/poetry-feedstock.

Also, for the next build we should change `importlib_metadata`→`importlib-metadata` to avoid the extraneous wrapper package.

**Comment by xylar** [comment]
I see, that seems like a good reason to do an arch build.

**Comment by xylar** [comment]
> The same consideration applies to https://github.com/conda-forge/poetry-feedstock

I'm guessing you mean that you already took care of these considerations in https://github.com/conda-forge/poetry-feedstock/pull/54?

**Comment by maresb** [comment]
> I'm guessing you mean that you already took care of these considerations

Ah, I was confused... I falsely assumed that `poetry-feedstock` was also noarch. The selector looks good to me.

Thanks so much @xylar for the PR and @ocefpaf for the quick review! I expect that it should fix my problems. I'll test it once the build hits the CDN. (In the unlikely event of further problems I'll open another issue.)

Thanks everyone! :smile:
